package com.transport.tracker.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
* A conditional alert message shown in the UI.
* Generated by AlertService based on threshold evaluation:
* - Delay > 15 min  → "Significant delays - Plan accordingly"
* - Disruption      → "Service alert - Check alternative routes"
* - Crowding HIGH   → "Vehicle at capacity - Consider next service"
* - Weather impact  → "Weather impact on schedule"
*/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AlertMessage {

    /**
     * Alert category: DELAY, DISRUPTION, CROWDING, WEATHER
     */
    private String type;

    /**
     * UI severity: INFO, WARNING, ERROR
     */
    private String level;

    /** Message to display to the user */
    private String message;

    /** Icon name/code for frontend rendering */
    private String icon;

    /** Associated route or stop ID for context */
    private String context;
}